<a href="https://colab.research.google.com/github/PremGorecki/MachineLearning/blob/main/01_MNIST_tmp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np


In [25]:
x = np.linspace(0, 100, 10) # start=0, end=100, steps=100
x

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [26]:
x.shape

(10,)

In [27]:
x1 = x.reshape(-1,5)
x1

array([[  0.        ,  11.11111111,  22.22222222,  33.33333333,
         44.44444444],
       [ 55.55555556,  66.66666667,  77.77777778,  88.88888889,
        100.        ]])

In [28]:
#Listy

pusta = []
pusta

[]

In [29]:
one = [1, 2]
two = [3, 4]
full = [one, two]
full

[[1, 2], [3, 4]]

In [30]:
full2 = one + two
full2

[1, 2, 3, 4]

In [31]:
# Seria - Series to seria taka trochę lista ze swoim indeksem
s = pd.Series(data=[3, 2, 4, 6])
s

0    3
1    2
2    4
3    6
dtype: int64

In [32]:
s2 = pd.Series(data=[3., np.nan, 4, 6], index=['a', 'b', 'c', 'd'], name = 'sample') 
s2

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [33]:
s2.shape

(4,)

In [34]:
#DataFrame
df = pd.DataFrame(data = [4, 5, 6], index=['first', 'second', 'third'], columns=['col_1'])
df

col_1
first       4
second      5
third       6

In [35]:
df2 = pd.DataFrame(s2)
df2

sample
a     3.0
b     NaN
c     4.0
d     6.0

In [36]:
df.index

Index(['first', 'second', 'third'], dtype='object')

In [37]:
df.values

array([[4],
       [5],
       [6]])

In [40]:
df.value_counts()

col_1
4        1
5        1
6        1
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, first to third
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   3 non-null      int64
dtypes: int64(1)
memory usage: 156.0+ bytes


In [42]:
#Macierz 
array = np.array([[2, 6, 3],
                  [5, -3, 4]])
array

array([[ 2,  6,  3],
       [ 5, -3,  4]])

In [44]:
array2 = np.array(df)
array2

array([[4],
       [5],
       [6]])

In [45]:
array2.shape

(3, 1)